#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"

struct RobotMap
{
	static const uint32_t
<<<<<<< HEAD
		LEFT_FRONT_TALON = 7,
		LEFT_REAR_TALON = 6,
		RIGHT_FRONT_TALON = 3,
		RIGHT_REAR_TALON = 2,
		GRABBER_TALON = 4,
		ROLLER_TALON = 5,
		GRABBER_ENCODER_A = 0,
		GRABBER_ENCODER_B = 1,
		FIRE_MOTOR = 0,
		WHEELS_MOTOR = 1,
		GRABBER_LOW_LIMIT = 1,
		GRABBER_HIGH_LIMIT = 0,
		GRABBER_CAN_TALON = 0;
=======
		LEFT_FRONT_TALON = 0,
		LEFT_REAR_TALON = 1,
		RIGHT_FRONT_TALON = 2,
		RIGHT_REAR_TALON = 3,
		LEFT_JOYSTICK = 4,
		GRABBER_TALON = 0,
		ROLLER_TALON = 1,
		GRABBER_ENCODER_A = 0,
		GRABBER_ENCODER_B = 0,
		FIRE_MOTOR = 5,
		WHEELS_MOTOR = 6;
>>>>>>> origin/master
};

#endif
